USE RecursosAdicionais;
SELECT DATACOTACAO,[USB,[EUR],[LIB] 
FROM
(SELECT DATACOTACAO,CODMOEDA,VALORCOTACAO FROM CotacoesPorDataMoeda) 
AS PV 
PIVOT (
AVG(VALORCOTACAO)FRO CODMOEDA IN([USD],[LIB],[EUR])
) AS P
SELECT * FROM INVESTIDORES;
SELECT BANCO,ANO,TIPO,VALOR FROM INVESTIDORES UNPIVOT(VALOR FOR TIPO IN(INVESTIMENTO,DESPESAS)) AS UPV ORDER BY BANCO,ANO TIPO;