USE SISDEP;
SELECT
 IDMATRICULA,NOMEFUNCIONARIO,SALARIO,ADMISSAO,FLOOR(CAST((GETDATE()-ADMISSAO) AS FLOAT) / 365.25)
  AS [TIME OF WORK] FROM FUNCIONARIO
  ALTER TABLE FUNCIONARIO ADD TEMPOSERVICO AS FLOOR(CAST((GETDATE()-ADMISSAO) AS FLOAT)/365.25)
  SELECT IDMATRICULA,NOMEFUNCIONARIO,SALARIO,ADMISSAO,TEMPOSERVICO FROM FUNCIONARIO