EXEC sp_attach_db 
 @dbname    = 'PEDIDOS',   
 @filename1 = 'c:\Dados\PEDIDOS_TABELAS.mdf', 
 @filename2 = 'c:\Dados\PEDIDOS_INDICES.ndf', 
 @filename3 = 'c:\Dados\PEDIDOS_log.ldf'
 USE PEDIDOS;
 SELECT * FROM TB_PEDIDO WHERE 
 CODVEN = (SELECT CODVEN FROM TB_VENDEDOR WHERE NOME = 'MARCELO')
  AND DATA_EMISSAO BETWEEN '2014-01-01' AND '2014-01-31';

  SELECT  C.NOME,V.NOME FROM TB_PEDIDO  P JOIN TB_CLIENTE C 
  ON C.CODCLI = P.CODCLI JOIN TB_VENDEDOR V ON V.CODVEN = P.CODVEN 
  WHERE  YEAR(DATA_EMISSAO) =2014 AND MONTH(DATA_EMISSAO) =1;

  SELECT P.NUM_PEDIDO,PP.DESCRICAO,C.NOME,V.NOME,IIP.QUANTIDADE FROM TB_PEDIDO P JOIN TB_ITENSPEDIDO IIP 
  ON IIP.NUM_PEDIDO = P.NUM_PEDIDO JOIN TB_CLIENTE C 
  ON C.CODCLI = P.CODCLI JOIN TB_VENDEDOR V 
  ON V.CODVEN = P.CODVEN JOIN TB_PRODUTO PP 
  ON PP.COD_PRODUTO = IIP.COD_PRODUTO WHERE IIP.DESCONTO > 7;
  
  SELECT COUNT(*),
  MIN(VLR_TOTAL),
  MAX(VLR_TOTAL) FROM TB_PEDIDO 
  WHERE DATA_EMISSAO BETWEEN '2014-01-01' AND '2014-01-31';
  
  SELECT SUM(P.VLR_TOTAL) AS [VALOR TOTAL],
  (SUM(P.VLR_TOTAL)*V.PORC_COMISSAO)/100 AS COMISSAO,V.NOME  
  FROM TB_VENDEDOR V JOIN TB_PEDIDO P ON P.CODVEN = V.CODVEN GROUP BY V.NOME,V.PORC_COMISSAO
  


  SELECT TOP 10  C.NOME,V.VLR_TOTAL FROM TB_PEDIDO V JOIN TB_CLIENTE C 
  ON C.CODCLI = V.CODCLI 
  ORDER BY V.VLR_TOTAL DESC;

  SELECT NOME FROM TB_CLIENTE 
  WHERE CODCLI NOT IN 
  (SELECT V.CODCLI FROM TB_PEDIDO V WHERE DATA_EMISSAO BETWEEN '2014-01-01' AND '2014-01-31'); 
  
UPDATE TB_PRODUTO SET PRECO_VENDA = PRECO_CUSTO*1.2 WHERE COD_TIPO=5;

UPDATE TB_PRODUTO SET PRECO_VENDA = PRECO_CUSTO *1.4   WHERE 
COD_PRODUTO IN (SELECT COD_PRODUTO FROM TB_TIPOPRODUTO WHERE DESCRICAO='REGUA');

USE PEDIDOS;
SELECT * INTO PRODUTOS_COPIA FROM TB_PRODUTO;
SELECT * FROM PRODUTOS_COPIA;
DELETE FROM PRODUTOS_COPIA WHERE COD_TIPO = (SELECT COD_TIPO FROM TB_TIPOPRODUTO WHERE TIPO ='CANETA ') ;
