SELECT * FROM SYSTYPES;
--VIEW
SELECT * FROM SYS.TYPES;
CREATE DATABASE UDDT;
GO
USE UDDT;
--TYPE DATA
CREATE TYPE NOMEPESSOA FROM VARCHAR(50) NOT NULL;
CREATE TYPE VALORMONEY FROM DECIMAL(10,2) NOT NULL;
CREATE TYPE OPCAOSN FROM CHAR(1) NOT NULL;
CREATE TYPE REGRESS FROM DATE NULL;
--VER SE FOI
SELECT * FROM SYSTYPES WHERE uid='1';
--CONSTRAINT
GO
CREATE RULE R_VAL AS @VALOR >= 0;
GO
CREATE RULE R_OPSN AS @SN IN('S','N');
GO
CREATE RULE R_DATE AS @DATA BETWEEN '2014-01-01' AND GETDATE();
GO
--VER REGRAS 
SELECT * FROM SYSOBJECTS WHERE xtype='R';
--ASSOCIAR RULES 
EXEC sp_bindrule 'R_VAL','VALORMONEY';
EXEC sp_bindrule 'R_OPSN', 'OPCAOSN';
EXEC sp_bindrule 'R_DATE','REGRESS';

--DEFAULT
go
CREATE DEFAULT def_sn as 's';
GO
CREATE DEFAULT DEF_DATE AS GETDATE();
GO
--CONSULTA DE  DEFAULT
SELECT * FROM SYSOBJECTS WHERE XTYPE='D';
--ASSOCIAR DEFAULT
EXEC sp_bindefault 'DEF_DATE','REGRESS';
EXEC sp_bindefault 'DEF_DATE','OPCAOSN';
--SEQUENCIAL(IDENTITY PERSONALIZADO)
CREATE SEQUENCE SEQ_REGI 
START WITH 123 INCREMENT BY 10
MINVALUE 10 
MAXVALUE 100000000
CYCLE 
--SEE THE SEQUENCE
SELECT * FROM SYS.sequences;
--EXEMPLO
CREATE TABLE CLIENTE(
ID INT IDENTITY PRIMARY KEY,
NOME  NOMEPESSOA,
STATUSATIVO OPCAOSN,
CADASTROCLI REGRESS
);
CREATE  TABLE FORNECEDOR (
ID INT PRIMARY KEY,
NOMEFORNC NOMEPESSOA,
STATUSS OPCAOSN,
CADFORNC REGRESS

);
--INSERINDO DADOS
INSERT INTO CLIENTE (ID,NOME) VALUES(NEXT VALUE FOR DBO.SEQ_REGI,'NICOLAS');