--1
CREATE TYPE TIPO_CODIGO FROM INT NOT NULL;
CREATE TYPE TIPO_ENDERECO FROM VARCHAR(60) NULL;
CREATE TYPE TIPO_FONE FROM CHAR(14) NULL;
CREATE TYPE TIPO_SEXO FROM CHAR(1) NOT NULL;
CREATE TYPE TIPO_ALIQUOTA FROM NUMERIC(4,2) NULL;
CREATE TYPE TIPO_PRAZO FROM INT NOT NULL;
--2
SELECT * FROM SYSTYPES WHERE UID=1
--3
GO
CREATE RULE R_SEXO AS @RE IN ('M','F');
GO
CREATE RULE R_ALIQUOTA AS @ALI >=0;
GO
CREATE RULE R_PRAZO AS @PRA BETWEEN 1 AND 60;
GO
SELECT * FROM SYSOBJECTS WHERE XTYPE ='R';
EXEC SP_BINDRULE R_SEXO , TIPO_SEXO;
GO
EXEC sp_bindrule R_ALIQUOTA,TIPO_ALIQUOTA;
GO
EXEC sp_bindrule R_PRAZO,TIPO_PRAZO;
--6
GO
CREATE DEFAULT D_SEXO AS   'M';
GO
CREATE DEFAULT D_ALIQUOTA AS   0;
GO
CREATE DEFAULT D_PRAZO AS 1;
GO
--7
SELECT * FROM SYSOBJECTS WHERE XTYPE='D';
--8
EXEC sp_bindefault D_SEXO , TIPO_SEXO;
EXEC sp_bindefault D_ALIQUOTA,TIPO_ALIQUOTA;
EXEC sp_bindefault D_PRAZO, TIPO_PRAZO;
--9
CREATE TABLE PESSOAS(
COD_PESSOA TIPO_CODIGO PRIMARY KEY,
NOME VARCHAR(60),
ENDERECO TIPO_ENDERECO,
SEXO TIPO_SEXO
--10
);
CREATE TABLE CONTAS(
COD_CONTA TIPO_CODIGO PRIMARY KEY,
VALOR NUMERIC(10,2),
QTD_PARCELA TIPO_PRAZO,
PORC_MULTA TIPO_ALIQUOTA
);
--11
INSERT INTO PESSOAS VALUES(1,'GUSTAVO','RUA ENDINALDO','M'),
(2,'GUSTAVO','RUA TANCREDO','M'),
(3,'FERNANDA','RUA LEONARDO','F'),
(4,'LETICIA','RUA GASPAR','F'),
(5,'GUILERME','RUA ELGENIO','M');
--12
SELECT * FROM PESSOAS;
--13
CREATE TABLE FUNCIONARIO(
COD_FUNC TIPO_CODIGO PRIMARY KEY,
NOME VARCHAR(30),
ENDERECO VARCHAR(80),
SEXO TIPO_SEXO

);
--14 
CREATE SYNONYM FUNCTIONARIO FOR DBO.FUNCIONARIO;
--15
CREATE SEQUENCE SQ_FUNC 
START WITH 100
INCREMENT BY 1;
INSERT INTO FUNCIONARIO(COD_FUNC,NOME,ENDERECO,SEXO) VALUES (NEXT VALUE FOR DBO.SQ_FUNC,'GIUDA','RUA PEIXOTO','F');

--LAB2 