USE DB_AULA_IMPACTA;
SELECT DB_NAME();
SELECT * FROM SYSOBJECTS;
SELECT * FROM SYS.linked_logins;
EXEC sp_helpfile;
EXEC sp_helplogins;
-- LAB3
SELECT NAME FROM SYS.TABLES;
SELECT * FROM SYSOBJECTS WHERE xtype='V';
SELECT * FROM SYSCOLUMNS WHERE OBJECT_NAME(ID)='TB_CLIENTE';
EXEC SP_HELP TB_PEDIDO;
